### ISSUE TITLE
dhcp is not working

### ISSUE THREAD

**Issue by Nooxm** [oresterosso75/Alpine_PPPwn-Luckfox#1]
![10](https://github.com/oresterosso75/Alpine_PPPwn-Luckfox/assets/11632464/a69a9b2c-2459-415c-9236-015f3d9fcefe)

**Comment by oresterosso75** [comment]
Il messaggio di errore che stai ricevendo (udhcpc failed to get a dhcp lease) indica che il client DHCP udhcpc non è riuscito a ottenere un lease DHCP dal server.
1. Verifica l'Interfaccia di Rete
Assicurati che l'interfaccia di rete sia correttamente configurata e attiva. Puoi controllare lo stato delle interfacce di rete con:

`ip link show`

2. Configurazione dell'Interfaccia di Rete
Verifica che il file di configurazione per la tua interfaccia di rete (solitamente eth0) sia configurato per utilizzare DHCP. Su Alpine Linux, puoi controllare e modificare il file /etc/network/interfaces.

`auto eth0
iface eth0 inet dhcp`

3. Riavvio del Servizio di Rete
Dopo aver verificato la configurazione, riavvia il servizio di rete per applicare le modifiche:

`/etc/init.d/networking restart`
